service:
  name: ifttt-office

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    SLACK_WEBHOOK_URL: ${ssm:iftttOfficeSlackEndpoint}

functions:
  departed:
    handler: handler.onDeparted
    events:
      - http:
          method: post
          path: departed
